# Generated by Django 6.0.4 on 2026-04-27 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormulaRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("att_name", models.CharField(max_length=255)),
                ("formula", models.CharField(max_length=500)),
                ("reevaluate_on_update", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formula Registry",
                "verbose_name_plural": "Formula Registries",
                "unique_together": {("content_type", "att_name")},
            },
        ),
    ]
