# Generated by Django 6.0.4 on 2026-04-26 16:27

import django_formulafield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sold", models.IntegerField()),
                ("cost_per_sale", models.FloatField()),
                ("total_per_sale", models.FloatField()),
                (
                    "placeholder_1_formula",
                    models.CharField(
                        help_text="e.g. (sold * total_per_sale) - (sold * cost_per_sale)",
                        max_length=500,
                    ),
                ),
                (
                    "placeholder_1",
                    django_formulafield.fields.EvaluatedFormulaField(
                        blank=True,
                        formula_field="formula",
                        null=True,
                        reevaluate_on_update=True,
                    ),
                ),
                (
                    "placeholder_2_formula",
                    models.CharField(
                        help_text="e.g. (sold * total_per_sale) - (sold * cost_per_sale)",
                        max_length=500,
                    ),
                ),
                (
                    "placeholder_2",
                    django_formulafield.fields.EvaluatedFormulaField(
                        blank=True,
                        formula_field="formula",
                        null=True,
                        reevaluate_on_update=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Performance",
                "verbose_name_plural": "Sales Performances",
            },
        ),
    ]
