# Generated by Django 6.0.4 on 2026-04-26 17:24

import django_formulafield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulasample", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesperformance",
            name="product",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="salesperformance",
            name="product_category",
            field=models.CharField(
                choices=[("shoes", "Shoes"), ("electronics", "Electronics")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesperformance",
            name="placeholder_1",
            field=django_formulafield.fields.EvaluatedFormulaField(
                blank=True,
                formula_field="placeholder_1_formula",
                null=True,
                reevaluate_on_update=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesperformance",
            name="placeholder_2",
            field=django_formulafield.fields.EvaluatedFormulaField(
                blank=True,
                formula_field="placeholder_2_formula",
                null=True,
                reevaluate_on_update=True,
            ),
        ),
    ]
