# Generated by Django 6.0.4 on 2026-04-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulasample", "0002_salesperformance_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesperformance",
            name="registry_kpi_1",
            field=models.CharField(
                blank=True,
                help_text="Managed by FormulaRegistry. Do not edit manually.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="salesperformance",
            name="registry_kpi_2",
            field=models.CharField(
                blank=True,
                help_text="Managed by FormulaRegistry. Do not edit manually.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesperformance",
            name="placeholder_1_formula",
            field=models.CharField(
                blank=True,
                help_text="Per-instance formula. e.g. (sold * total_per_sale) - (sold * cost_per_sale)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesperformance",
            name="placeholder_2_formula",
            field=models.CharField(
                blank=True,
                help_text='Per-instance formula. e.g. IF(sold > 100, "good", "bad")',
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesperformance",
            name="product",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="salesperformance",
            name="product_category",
            field=models.CharField(
                blank=True,
                choices=[("shoes", "Shoes"), ("electronics", "Electronics")],
                max_length=255,
                null=True,
            ),
        ),
    ]
